In [1]:
import pandas as pd
df = pd.read_table('https://raw.githubusercontent.com/sinanuozdemir/SF_DAT_15/master/data/sms.tsv',
                   sep='\t', header=None, names=['label', 'msg'])

In [2]:
df.head(30)

label                                                msg
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...
5   spam  FreeMsg Hey there darling it's been 3 week's n...
6    ham  Even my brother is not like to speak with me. ...
7    ham  As per your request 'Melle Melle (Oru Minnamin...
8   spam  WINNER!! As a valued network customer you have...
9   spam  Had your mobile 11 months or more? U R entitle...
10   ham  I'm gonna be home soon and i don't want to tal...
11  spam  SIX chances to win CASH! From 100 to 20,000 po...
12  spam  URGENT! You have won a 1 week FREE membership ...
13   ham  I've been searching for the right words to tha...
14   ham                I HAVE A DATE ON SUNDAY WITH WILL!!
15  spam  XXXMobileMovieClub: To use your credit, click ...
16   ham                         Oh k...i'm watching here:)
17   ham  Eh u remember how 2 spell his name... Yes i di...
18   ham  Fine if that’s the way u feel. That’s the way ...
19  spam  England v Macedonia - dont miss the goals/team...
20   ham          Is that seriously how you spell his name?
21   ham    I‘m going to try for 2 months ha ha only joking
22   ham  So ü pay first lar... Then when is da stock co...
23   ham  Aft i finish my lunch then i go str down lor. ...
24   ham  Ffffffffff. Alright no way I can meet up with ...
25   ham  Just forced myself to eat a slice. I'm really ...
26   ham                     Lol your always so convincing.
27   ham  Did you catch the bus ? Are you frying an egg ...
28   ham  I'm back &amp; we're packing the car now, I'll...
29   ham  Ahhh. Work. I vaguely remember that! What does...

In [3]:
df.label.value_counts()

ham     4825
spam     747
Name: label, dtype: int64

In [4]:
df.msg.describe()


count                       5572
unique                      5169
top       Sorry, I'll call later
freq                          30
Name: msg, dtype: object

In [5]:
df['label'] = df.label.map({'ham':0, 'spam':1})
df.head()

label                                                msg
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [6]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.msg, df.label, random_state=1)
X_train.shape
X_test.shape

(1393,)

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

In [67]:
train_simple = ['call you tonight',
                'Call me a cab',
                'please call me... PLEASE 44!']

In [68]:
vect = CountVectorizer()
vect.fit(train_simple)
vect.get_feature_names()

[u'44', u'cab', u'call', u'me', u'please', u'tonight', u'you']

In [69]:
train_simple_dtm = vect.transform(train_simple)
train_simple_dtm
train_simple_dtm.toarray()

array([[0, 0, 1, 0, 0, 1, 1],
       [0, 1, 1, 1, 0, 0, 0],
       [1, 0, 1, 1, 2, 0, 0]])

In [70]:
pd.DataFrame(train_simple_dtm.toarray(), \
columns=vect.get_feature_names())

44  cab  call  me  please  tonight  you
0   0    0     1   0       0        1    1
1   0    1     1   1       0        0    0
2   1    0     1   1       2        0    0

In [71]:
test_simple = ["please don't call me"]
test_simple_dtm = vect.transform(test_simple)
test_simple_dtm.toarray()
pd.DataFrame(test_simple_dtm.toarray(), columns=vect.get_feature_names())


44  cab  call  me  please  tonight  you
0   0    0     1   1       1        0    0

In [72]:
vect = CountVectorizer()

In [73]:
train_dtm = vect.fit_transform(X_train)
train_dtm

<4179x7456 sparse matrix of type '<type 'numpy.int64'>'
	with 55209 stored elements in Compressed Sparse Row format>

In [74]:
test_dtm = vect.transform(X_test)
test_dtm

<1393x7456 sparse matrix of type '<type 'numpy.int64'>'
	with 17604 stored elements in Compressed Sparse Row format>

In [77]:
train_features = vect.get_feature_names()
len(train_features)
train_features[:50];

In [78]:
train_arr = train_dtm.toarray()
train_arr

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [42]:
3**2

9

In [79]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr[0, 0]
arr[1, 3]
arr[0, :]
arr[:, 0]
np.sum(arr)
np.sum(arr, axis=0)
np.sum(arr, axis=1)

array([10, 26])

In [80]:
X_train[0]
sum(train_arr[0, :])

24

In [82]:
#Same as np.sum(arr, axis=1)
sum(arr[1, :])

26

In [83]:
from sklearn.naive_bayes import MultinomialNB
nb=MultinomialNB()
nb.fit(train_dtm, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [84]:
preds = nb.predict(test_dtm)
preds

array([0, 0, 0, ..., 0, 1, 0])

In [86]:
train_dtm[1]

<1x7456 sparse matrix of type '<type 'numpy.int64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [87]:
from  sklearn import metrics
print metrics.accuracy_score(y_test, preds)

0.988513998564


In [88]:
print metrics.confusion_matrix(y_test, preds)

[[1203    5]
 [  11  174]]


In [89]:
probs = nb.predict_proba(test_dtm)[:, 1]

In [90]:
probs

array([  2.87744864e-03,   1.83488846e-05,   2.07301295e-03, ...,
         1.09026171e-06,   1.00000000e+00,   3.98279868e-09])

In [91]:
print metrics.roc_auc_score(y_test, probs)

0.986643100054


In [92]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()

In [94]:
all_dtm = vect.fit_transform(df.msg)

from sklearn.cross_validation import cross_val_score
cross_val_score(logreg, all_dtm, df.label, cv=10, scoring='roc_auc').mean()


0.98815431206573179

In [95]:
cross_val_score(nb, all_dtm, df.label, cv=10, scoring='roc_auc').mean()


0.98327573900025644

In [96]:
vect = CountVectorizer(stop_words='english', ngram_range=[1,5]) 


In [97]:
train_dtm = vect.fit_transform(X_train)
train_dtm

<4179x86489 sparse matrix of type '<type 'numpy.int64'>'
	with 129114 stored elements in Compressed Sparse Row format>

In [98]:
test_dtm = vect.transform(X_test)

In [99]:
nb = MultinomialNB()
nb.fit(train_dtm, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [100]:
preds = nb.predict(test_dtm)


In [101]:
print metrics.accuracy_score(y_test, preds)
print metrics.confusion_matrix(y_test, preds)

0.990667623833
[[1207    1]
 [  12  173]]


In [102]:
all_dtm = vect.fit_transform(df.msg)

In [103]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()

In [104]:
gettysburg ='Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal. \
Now we are engaged in a great civil war, testing whether that nation, or any nation so conceived and so dedicated, can long endure. We are met on a great battle-field of that war. We have come to dedicate a portion of that field, as a final resting place for those who here gave their lives that that nation might live. It is altogether fitting and proper that we should do this. \
But, in a larger sense, we can not dedicate -- we can not consecrate -- we can not hallow -- this ground. The brave men, living and dead, who struggled here, have consecrated it, far above our poor power to add or detract. The world will little note, nor long remember what we say here, but it can never forget what they did here. It is for us the living, rather, to be dedicated here \
to the unfinished work which they who fought here have thus far so nobly advanced. It is rather for us to be here dedicated to the great task remaining before us -- that from these honored dead we take increased devotion to that cause for which they gave the last full measure of devotion -- that we here highly resolve that these dead shall not have died in vain -- that this nation, \
under God, shall have a new birth of freedom -- and that government of the people, by the people, for the people, shall not perish from the earth.'

In [107]:
vect = CountVectorizer() 
print df.msg

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
5       FreeMsg Hey there darling it's been 3 week's n...
6       Even my brother is not like to speak with me. ...
7       As per your request 'Melle Melle (Oru Minnamin...
8       WINNER!! As a valued network customer you have...
9       Had your mobile 11 months or more? U R entitle...
10      I'm gonna be home soon and i don't want to tal...
11      SIX chances to win CASH! From 100 to 20,000 po...
12      URGENT! You have won a 1 week FREE membership ...
13      I've been searching for the right words to tha...
14                    I HAVE A DATE ON SUNDAY WITH WILL!!
15      XXXMobileMovieClub: To use your credit, click ...
16                             Oh k...i'm watching here:)
17      Eh u r

In [106]:
vect.fit(gettysburg)
all_features = vect.get_feature_names()


ValueError: empty vocabulary; perhaps the documents only contain stop words