In [1]:
5*4

20

In [2]:
"""Previous results can be referred to, like Mathematica's %"""
x=_

In [3]:
x

20

In [4]:
a=[1,2,3,4,5]

In [5]:
b=enumerate(a)

In [6]:
b

In [9]:
for i, item in enumerate(b):
    print i, item

0 (0, 1)
1 (1, 2)
2 (2, 3)
3 (3, 4)
4 (4, 5)


In [10]:
b=['z', 'y', 'x', 't', 'u']

In [11]:
"""Equivalent to Mathematica's riffle"""
c=zip(a, b)

In [12]:
c

[(1, 'z'), (2, 'y'), (3, 'x'), (4, 't'), (5, 'u')]

In [15]:
from itertools import izip, count

In [16]:
for i, numbers, letters in izip(count(), a, b):
    print i, numbers, letters

0 1 z
1 2 y
2 3 x
3 4 t
4 5 u


In [69]:
"""Standard way to manipulate lists."""
doubled = [item * 2 for item in a]
doubled

[2, 4, 6, 8, 10]

In [19]:
L = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
doubled = [[item * 2 for item in row] for row in L]

In [20]:
doubled

[[2, 4, 6], [8, 10, 12], [14, 16, 18]]

In [70]:
"""Another way to do list manipulation using lambda"""
# Triples every element of a list
def triple_list(L):
    return map(lambda x: 3*x, L)

In [72]:
triple=triple_list(a)
triple

[3, 6, 9, 12, 15]

In [21]:
""" To Flatten a matrix"""
[item for row in L for item in row]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
["even" if item % 2 == 0 else "odd" for item in a]

['odd', 'even', 'odd', 'even', 'odd']

In [24]:
[item for item in a if item % 2 == 0]

[2, 4]

In [25]:
"""You can make it a generator instead of a list if you're just going to be 
looping over the result. You do this by using round brackets instead of square ones:"""

L = ["zack desario", "giovanna thron", "ryan orban", "jonathan dinu"]
for name in (item.split()[0] for item in L):
    print name

zack
giovanna
ryan
jonathan


In [75]:
"""What is the difference between the following two arrays?"""
L = [(2, 4), (5, 3), (6, 8), (4, 1)]
L = [[2, 4], [5, 3], [6, 8], [4, 1]]
L.sort(key=lambda x: x[0])
L

[[2, 4], [4, 1], [5, 3], [6, 8]]

In [76]:
L.sort(key=lambda x: x[1])
L

[[4, 1], [5, 3], [2, 4], [6, 8]]

In [77]:
L = [0, 5, -8, 9, -3, -2]
M = map(abs, L)
M

[0, 5, 8, 9, 3, 2]

In [36]:
map(lambda x: x if x > 0 else -x, L)

[0, 5, 8, 9, 3, 2]

In [79]:
f=lambda x, y: x+y
f(2,4)

6

In [81]:
Celsius = [39.2, 36.5, 37.3, 37.8]
Fahrenheit = map(lambda x: round((float(9)/5)*x + 32, 2), Celsius)
print Fahrenheit

[102.56, 97.7, 99.14, 100.04]


In [83]:
C = map(lambda x: round((float(5)/9)*(x-32)), Fahrenheit)
print C

[39.0, 37.0, 37.0, 38.0]


In [85]:
fib = [0,1,1,2,3,5,8,13,21,34,55]
result = filter(lambda x: x % 2==0, fib)
print result

[0, 2, 8, 34]


In [37]:
def sum(L):
    total = 0
    for x in L:
        total += x
    return total

def sum2(L):
    return reduce(lambda total, x: total + x, L)

In [41]:
sum2(M)

27

In [42]:
def len2(L):
    return reduce(lambda total, x: total + 1, L, 0)

In [44]:
len2(L)

6

In [86]:
lst = ['a', 'b', 'c', 'a', 'a', 'b', 'a', 'a']
d={}
for i, item in enumerate(lst):
    if item in d:
        d[item].append(i)
    else:
        d[item]=[i]
        
"""How do I create a function that simply counts how many occurences of each item??"""
d

{'a': [0, 3, 4, 6, 7], 'b': [1, 5], 'c': [2]}

In [87]:
f = lambda a,b: a if (a > b) else b
reduce(f, [47,11,42,102,13])

102

In [88]:
reduce(lambda x, y: x+y, range(1,101))

5050

In [54]:
from collections import defaultdict
f=defaultdict(list)
for i, item in enumerate(lst):
    f[item].append(i)

In [58]:
string = "Hello cherry rocking momma Hello"

In [59]:
s = set()
for word in string.split():
    if len(word) > 3:
        s.add(word)
        
"""How do you check membership of a set?"""

In [60]:
s

{'Hello', 'cherry', 'momma', 'rocking'}

In [64]:
b=set(string.split())
c=set(['momma'])
b.intersection(c)

{'momma'}

In [67]:
from itertools import permutations, combinations
L=[1, 2, 3, 4]
for item in permutations(L):
    print item

(1, 2, 3, 4)
(1, 2, 4, 3)
(1, 3, 2, 4)
(1, 3, 4, 2)
(1, 4, 2, 3)
(1, 4, 3, 2)
(2, 1, 3, 4)
(2, 1, 4, 3)
(2, 3, 1, 4)
(2, 3, 4, 1)
(2, 4, 1, 3)
(2, 4, 3, 1)
(3, 1, 2, 4)
(3, 1, 4, 2)
(3, 2, 1, 4)
(3, 2, 4, 1)
(3, 4, 1, 2)
(3, 4, 2, 1)
(4, 1, 2, 3)
(4, 1, 3, 2)
(4, 2, 1, 3)
(4, 2, 3, 1)
(4, 3, 1, 2)
(4, 3, 2, 1)


In [68]:
for comb in combinations(L, 3):
    print comb

(1, 2, 3)
(1, 2, 4)
(1, 3, 4)
(2, 3, 4)


In [89]:
print "."*10

..........


In [90]:
print "How old are you?",
age = raw_input()
print "How tall are you?",
height = raw_input()
print "How much do you weigh?",
weight = raw_input()

print "So, you're %r old, %r tall and %r heavy." % (
    age, height, weight)

How old are you?37
 How tall are you?6'4
 How much do you weigh?198
 So, you're '37' old, "6'4" tall and '198' heavy.


In [91]:
from sys import argv

script, user_name = argv
prompt = '> '

print "Hi %s, I'm the %s script." % (user_name, script)
print "I'd like to ask you a few questions."
print "Do you like me %s?" % user_name
likes = raw_input(prompt)

print "Where do you live %s?" % user_name
lives = raw_input(prompt)

print "What kind of computer do you have?"
computer = raw_input(prompt)

print """
Alright, so you said %r about liking me.
You live in %r.  Not sure where that is.
And you have a %r computer.  Nice.
""" % (likes, lives, computer)

ValueError: too many values to unpack

In [92]:
# this one is like your scripts with argv
def print_two(*args):
    arg1, arg2 = args
    print "arg1: %r, arg2: %r" % (arg1, arg2)

# ok, that *args is actually pointless, we can just do this
def print_two_again(arg1, arg2):
    print "arg1: %r, arg2: %r" % (arg1, arg2)

# this just takes one argument
def print_one(arg1):
    print "arg1: %r" % arg1

# this one takes no arguments
def print_none():
    print "I got nothin'."


print_two("Zed","Shaw")
print_two_again("Zed","Shaw")
print_one("First!")
print_none()

arg1: 'Zed', arg2: 'Shaw'
arg1: 'Zed', arg2: 'Shaw'
arg1: 'First!'
I got nothin'.


In [1]:
def fizzbuzz(lengthy):
    for item in range(lengthy):
        print item
        if item % 3 == 0 & item % 5 == 0:
            print "fizzbuzz"
        elif item % 3 ==0:
            print "fizz"
        elif item % 5 ==0:
            print "buzz"
        else:
            continue
            
fizzbuzz(10)

0
fizzbuzz
1
2
3
fizzbuzz
4
5
buzz
6
fizzbuzz
7
8
9
fizzbuzz


In [2]:
def computeEmail(string):
    bbb=string.split('@')
    if len(bbb)>1:
        ccc=bbb[1].split('.')
        if len(ccc) > 1:
            return True
        else:
            return False
    else:
        return False

In [3]:
def fib(n):
    if n < 2:
        return n
    return fib(n-2) + fib(n-1)

print map(fib, range(1, 10))

[1, 1, 2, 3, 5, 8, 13, 21, 34]


In [ ]:
s = raw_input()

vowels = 'AEIOU'

kevsc = 0
stusc = 0
for i in range(len(s)):
    if s[i] in vowels:
        kevsc += (len(s)-i)
    else:
    #print (i)
    #print stusc
        stusc += (len(s)-i)

#print stusc
if kevsc > stusc:
    print "Kevin", kevsc
elif kevsc < stusc:
    print "Stuart", stusc
else:
    print "Draw"

In [8]:
def fibo(N):
    fibo=[0,1]
    for i in range(2, N):
        fibo.append(fibo[i-1]+fibo[i-2])
    return fibo

In [10]:
cubed = lambda a: round(a**3)
map(cubed, fibo(10))

[0.0, 1.0, 1.0, 8.0, 27.0, 125.0, 512.0, 2197.0, 9261.0, 39304.0]

In [11]:
#Add complex numbers / vectors together

def addThings(x, ix, y, iy):
    print ([x+y, ix + iy])

addThings(1,2,3,4)

[4, 6]


In [12]:
a = ([[1,2,3],[4,5,6],[0,0,1]]); 
a = sorted(a, key=lambda a_entry: a_entry[1]) 
print a

[[0, 0, 1], [1, 2, 3], [4, 5, 6]]


In [13]:
def multipliers():
    return [lambda x : i * x for i in range(4)]
    
print [m(2) for m in multipliers()]

[6, 6, 6, 6]


In [15]:
multipliers(7)

TypeError: multipliers() takes no arguments (1 given)

In [16]:
def extendList(val, list=[]):
    list.append(val)
    return list

list1 = extendList(10)
list2 = extendList(123,[])
list3 = extendList('a')

print "list1 = %s" % list1
print "list2 = %s" % list2
print "list3 = %s" % list3

list1 = [10, 'a']
list2 = [123]
list3 = [10, 'a']


In [17]:
list1

[10, 'a']

In [19]:
# However, what actually happens is that the new default list is created only once 
# when the function is defined, and that same list is then used subsequently whenever 
# extendList is invoked without a list argument being specified. 
# This is because expressions in default arguments are calculated when the 
# function is defined, not when it’s called.
extendList(10)

[10, 'a', 10, 10]

In [ ]:
# Better to do
def extendList(val, list=None):
    if list is None:
        list = []
    list.append(val)
    return list

In [20]:
# The key to the answer is that, in Python, class variables are internally handled as 
# dictionaries. If a variable name is not found in the dictionary of the current class, 
# the class hierarchy (i.e., its parent classes) are searched until the referenced variable 
# name is found (if the referenced variable name is not found in the class itself or 
# anywhere in its hierarchy, an AttributeError occurs).

class Parent(object):
    x = 1

class Child1(Parent):
    pass

class Child2(Parent):
    pass

print Parent.x, Child1.x, Child2.x
Child1.x = 2
print Parent.x, Child1.x, Child2.x
Parent.x = 3
print Parent.x, Child1.x, Child2.x

1 1 1
1 2 1
3 2 3


In [21]:
def div1(x,y):
    print "%s/%s = %s" % (x, y, x/y)
    
def div2(x,y):
    print "%s//%s = %s" % (x, y, x//y)

div1(5,2)
div1(5.,2)
div2(5,2)
div2(5.,2.)

5/2 = 2
5.0/2 = 2.5
5//2 = 2
5.0//2.0 = 2.0


In [22]:
list = ['a', 'b', 'c', 'd', 'e']
print list[10:]

[]


In [41]:
X=['a', 'b', 'c']
Y=['a']
Z=['a','b']
Q=[X, Y, Z]
print Q[1 :]

[['a'], ['a', 'b']]


In [32]:
#Combinatorics
results=[['a'], ['b'], ['c']]
for q in Q[1:]:
    for i in q:
        for r in results:
            r.append(i)

In [33]:
results

[['a', 'a', 'a', 'b'], ['b', 'a', 'a', 'b'], ['c', 'a', 'a', 'b']]

In [46]:
results=[[]]
for q in Q:
    place = []
    for item in q:
        for r in results:
            #print r + [item]
            place.append(r + [item])
    results = place
    
results

[['a', 'a', 'a'],
 ['b', 'a', 'a'],
 ['c', 'a', 'a'],
 ['a', 'a', 'b'],
 ['b', 'a', 'b'],
 ['c', 'a', 'b']]

In [62]:
results=[['a'], ['b'], ['c']]
for q in Q[1:]:
    place = []
    for item in q:
        for r in results:
            print r
            place.append(r.append(item))
    results = place
    

['a']
['b']
['c']
None


AttributeError: 'NoneType' object has no attribute 'append'

In [55]:
results

[['a', 'a', 'a', 'b'], ['b', 'a', 'a', 'b'], ['c', 'a', 'a', 'b']]

In [59]:
list = [ [ ] ] * 5
list  # output?


[[], [], [], [], []]

In [60]:
list[0].append(10)
list  # output?


[[10], [10], [10], [10], [10]]

In [61]:
list[1].append(20)
list  # output?

[[10, 20], [10, 20], [10, 20], [10, 20], [10, 20]]

In [68]:
a=[1,4,3,6,3,4,8,9]
evenIndex=[]
even=[]
for i, item in enumerate(a):
    if i%2 == 0:
            evenIndex.append(item)
    if item%2 == 0:
            even.append(item)
print even
print evenIndex

[4, 6, 4, 8]
[1, 3, 3, 8]


In [69]:
a[::2] #This syntax takes the even indices from the list

[1, 3, 3, 8]

In [71]:
class DefaultDict(dict):
    def __missing__(self, key):
        return []

d = DefaultDict()
d['florp'] = 127

In [72]:
d

{'florp': 127}

In [76]:
def isPrime(n):
    for i in range(2,n):
        if n%i == 0:
            return False
    return True

In [80]:
isPrime(13)

True

In [83]:
''.join([str(x) for x in xrange(20)])

'012345678910111213141516171819'

In [85]:
import itertools
[x for x in itertools.permutations('123')]

[('1', '2', '3'),
 ('1', '3', '2'),
 ('2', '1', '3'),
 ('2', '3', '1'),
 ('3', '1', '2'),
 ('3', '2', '1')]

In [86]:
[x for x in itertools.permutations('123', 2)]

[('1', '2'), ('1', '3'), ('2', '1'), ('2', '3'), ('3', '1'), ('3', '2')]

In [89]:
list = ['a','b', 'c']
list.insert(2, 'q')
list

['a', 'b', 'q', 'c']

In [90]:
list.pop(2)

'q'

In [91]:
list

['a', 'b', 'c']

In [92]:
list.remove('c')

In [93]:
list

['a', 'b']

In [94]:
list.count('a')

1

In [95]:
list.reverse()
list

['b', 'a']

In [98]:
#lambda function does not need a return, always returns
lamb = lambda x: x**3
lamb(4)

64

In [101]:
addy = lambda x, y, z: x+y+z
addy(400, 30, 2)

432

In [102]:
zz=[1,1,2,3,4,4,5]
print(set(zz))

set([1, 2, 3, 4, 5])


In [104]:
map(lambda x,y: x*y, [1,2,3], [4,5,6])

[4, 10, 18]

In [105]:
noprimes = [j for i in range(2, 8) for j in range(i*2, 50, i)]
print noprimes

[4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 10, 15, 20, 25, 30, 35, 40, 45, 12, 18, 24, 30, 36, 42, 48, 14, 21, 28, 35, 42, 49]


In [108]:
sentence = 'I like cheese on my sandwich.'.split()
sentence

['I', 'like', 'cheese', 'on', 'my', 'sandwich.']

In [110]:
stuff = map(lambda w: [w, len(w)], sentence)
print stuff

[['I', 1], ['like', 4], ['cheese', 6], ['on', 2], ['my', 2], ['sandwich.', 9]]


In [111]:
def print_all(*args):
    for x in enumerate(args):
        print x
        
print_all('a','c', 'f')

(0, 'a')
(1, 'c')
(2, 'f')


In [114]:
def kargs_function(*args, **kargs):
    for k,v in kargs.items():
        print (k,v)
    for x in args:
        print x



In [116]:
kargs_function(4,5,6, hello='jimmy', you_Are='cool')

('hello', 'jimmy')
('you_Are', 'cool')
4
5
6


In [3]:
f = lambda x: x**3

In [4]:
f(3)

27

In [14]:
def fibobo(X):
    if X <= 1 :
        return 1
    else:
        return fibobo(X-1) + fibobo(X-2)
    

In [30]:
q = lambda x: x**3
map(q, map(fibobo, range(10)))

[1, 1, 8, 27, 125, 512, 2197, 9261, 39304, 166375]

In [41]:
phone = [' 07895 4621 30 ', '919875 641230', '9195969878']
for i in phone:
    print int("".join(i.split()))

7895462130
919875641230
9195969878


In [42]:
#You are given a space separated list of numbers. 
#Your task is to print a reversed NumPy array with the element type float.

a ='4 7 8 3 5 9 3 8'

In [54]:
result =[]
for item in a.split(" "):
    result.append(float(item))
    
result.sort(reverse=True)
    
print result

[9.0, 8.0, 8.0, 7.0, 5.0, 4.0, 3.0, 3.0]


In [58]:
result[::4]

[9.0, 5.0]

In [59]:
import numpy

my_array = numpy.array([1,2,3,4,5,6,7,8,9])
print numpy.reshape(my_array,(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [64]:
import numpy

print numpy.ones((1,2)) 

[[ 1.  1.]]


In [66]:
print numpy.eye(8, 7) 

[[ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [1]:
a=[1,4,3,5,2, 6]
sorted(a)

[1, 2, 3, 4, 5, 6]

In [2]:
towns = [{'name': 'Manchester', 'population': 58241}, {'name': 'Coventry', 'population': 12435}, {'name': 'South Windsor', 'population': 25709}]

In [9]:
# For loops...
town_names = []
for town in towns:
    town_names.append(town.get('name'))
# List comprehensions...
town_names = [town.get('name') for town in towns]
# Map function...
town_names = map(lambda town: town.get('name'), towns)

In [10]:
town_names

['Manchester', 'Coventry', 'South Windsor']

In [19]:
# Create two lists, one of the town names and one of the town populations using for loops... 
# using list comprehensions... using the zip() function

#town_names = []
#for town in towns:
#    town_names.append(town.get('name'))
    
#town_names = [town.get('name') for town in towns]

town_names, town_populations = zip(*[(town.get('name'), town.get('population')) for town in towns])

town_names, town_populations

(('Manchester', 'Coventry', 'South Windsor'), (58241, 12435, 25709))

In [24]:
town =[]
for i, item in enumerate(town_names):
    town.append((item, town_populations[i]))

dicty = dict(town)

town = [(town_name, town_populations[i]) for index, town_name in enumerate(town_names)]

In [26]:
dict(town)

{'Coventry': 25709, 'Manchester': 25709, 'South Windsor': 25709}

In [32]:
totalPop=0
totalPop2=[]
totalPop3 = []
for item in towns:
    totalPop += item.get('population')
    totalPop2.append(item.get('population'))
    
print sum(totalPop2)

q =reduce(lambda x, y : x+ y,    )

96385


TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'

In [37]:
totalPop3 = []

totalPop3.append(town.get('name') for town in towns )

In [38]:
    totalPop3

[<generator object <genexpr> at 0x10400ac30>]

In [39]:
def multipliers():
     return [lambda x : i * x for i in range(4)]
     
print [m(2) for m in multipliers()]

[6, 6, 6, 6]


In [42]:
m=multipliers()

In [49]:
m[3](1)

3